#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import ssl
import stat
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path
from typing import Any

from common import (
    BootstrapError,
    ensure_repo_root,
    prompt_secret,
    prompt_text,
    prompt_yes_no,
    run,
    run_streamed,
    section,
)


NODE_VERSION = "v24.16.0"
NODE_ARCHIVE = f"node-{NODE_VERSION}-linux-arm64.tar.xz"
NODE_URL = f"https://nodejs.org/dist/{NODE_VERSION}/{NODE_ARCHIVE}"
GITALIAS_REPO = "https://github.com/pisceskkk/gitalias.git"
RTK_LATEST_RELEASE_API = "https://api.github.com/repos/rtk-ai/rtk/releases/latest"
CLAUDE_PACKAGE = "@anthropic-ai/claude-code"
DEFAULT_DEEPSEEK_BASE_URL = "https://api.deepseek.com/anthropic"
DEFAULT_DEEPSEEK_MODEL = "deepseek-chat"
SHELL_BLOCK_BEGIN = "# >>> vllm-ascend-workspace bootstrap personal >>>"
SHELL_BLOCK_END = "# <<< vllm-ascend-workspace bootstrap personal <<<"


def tools_root(repo_root: Path) -> Path:
    root = repo_root / ".vaws-local" / "bootstrap" / "personal"
    root.mkdir(parents=True, exist_ok=True)
    return root


def node_root(repo_root: Path) -> Path:
    return tools_root(repo_root) / f"node-{NODE_VERSION}-linux-arm64"


def node_bin(repo_root: Path) -> Path:
    return node_root(repo_root) / "bin"


def download_file(url: str, dest: Path, *, insecure_ssl: bool = False) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".tmp")
    context = ssl._create_unverified_context() if insecure_ssl else None
    with urllib.request.urlopen(url, timeout=120, context=context) as response:
        with tmp.open("wb") as handle:
            shutil.copyfileobj(response, handle)
    os.replace(tmp, dest)


def fetch_json(url: str, *, insecure_ssl: bool = False) -> dict[str, Any]:
    context = ssl._create_unverified_context() if insecure_ssl else None
    with urllib.request.urlopen(url, timeout=120, context=context) as response:
        return json.loads(response.read().decode("utf-8"))


def install_node(repo_root: Path, *, force: bool = False) -> dict[str, Any]:
    root = node_root(repo_root)
    if root.exists() and (root / "bin" / "node").exists() and not force:
        return {"status": "already-present", "node_root": str(root)}
    archive = tools_root(repo_root) / NODE_ARCHIVE
    if not archive.exists() or force:
        download_file(NODE_URL, archive)
    extract_parent = tools_root(repo_root)
    with tarfile.open(archive, mode="r:xz") as tar:
        top_name = f"node-{NODE_VERSION}-linux-arm64"
        if root.exists():
            shutil.rmtree(root)
        tar.extractall(extract_parent)
        extracted = extract_parent / top_name
        if extracted != root:
            extracted.rename(root)
    return {"status": "installed", "node_root": str(root), "archive": str(archive)}


def configure_git_identity(*, user_name: str | None, user_email: str | None) -> dict[str, Any]:
    result: dict[str, Any] = {}
    if user_name:
        run(["git", "config", "--global", "user.name", user_name])
        result["user.name"] = user_name
    if user_email:
        run(["git", "config", "--global", "user.email", user_email])
        result["user.email"] = user_email
    return result


def configure_gitalias(repo_root: Path) -> dict[str, Any]:
    dest = tools_root(repo_root) / "gitalias"
    if dest.exists() and (dest / ".git").exists():
        run(["git", "-C", str(dest), "pull", "--ff-only"])
        status = "updated"
    else:
        if dest.exists():
            shutil.rmtree(dest)
        run(["git", "clone", GITALIAS_REPO, str(dest)])
        status = "cloned"
    alias_path = dest / "gitalias.txt"
    if not alias_path.exists():
        raise BootstrapError(f"gitalias file not found after clone: {alias_path}")
    existing = run(["git", "config", "--global", "--get-all", "include.path"], check=False)
    values = [line.strip() for line in existing.stdout.splitlines() if line.strip()]
    if str(alias_path) not in values:
        run(["git", "config", "--global", "--add", "include.path", str(alias_path)])
    return {"status": status, "path": str(alias_path)}


def personal_env_path() -> Path:
    return Path.home() / ".claude" / "bootstrap-env.sh"


def write_personal_env(
    repo_root: Path,
    *,
    deepseek_base_url: str,
    deepseek_model: str,
    deepseek_token: str,
) -> dict[str, Any]:
    env_path = personal_env_path()
    env_path.parent.mkdir(parents=True, exist_ok=True)
    node_bin_path = node_bin(repo_root)
    content = "\n".join(
        [
            "# Generated by vllm-ascend-workspace bootstrap.",
            "# Contains personal API credentials; keep this file private.",
            f"export PATH={json.dumps(str(node_bin_path))}:$PATH",
            "export NODE_TLS_REJECT_UNAUTHORIZED=0",
            "export IS_SANDBOX=1",
            f"export ANTHROPIC_BASE_URL={json.dumps(deepseek_base_url)}",
            f"export ANTHROPIC_AUTH_TOKEN={json.dumps(deepseek_token)}",
            f"export ANTHROPIC_API_KEY={json.dumps(deepseek_token)}",
            f"export ANTHROPIC_MODEL={json.dumps(deepseek_model)}",
            "alias cc='claude --dangerously-skip-permissions'",
            "",
        ]
    )
    env_path.write_text(content, encoding="utf-8")
    env_path.chmod(0o600)
    return {"path": str(env_path), "mode": oct(stat.S_IMODE(env_path.stat().st_mode))}


def update_bashrc(env_path: Path) -> dict[str, Any]:
    bashrc = Path.home() / ".bashrc"
    current = bashrc.read_text(encoding="utf-8") if bashrc.exists() else ""
    block = "\n".join(
        [
            SHELL_BLOCK_BEGIN,
            f'[ -f "{env_path}" ] && . "{env_path}"',
            SHELL_BLOCK_END,
            "",
        ]
    )
    if SHELL_BLOCK_BEGIN in current and SHELL_BLOCK_END in current:
        before, rest = current.split(SHELL_BLOCK_BEGIN, 1)
        _, after = rest.split(SHELL_BLOCK_END, 1)
        updated = before.rstrip() + "\n\n" + block + after.lstrip("\n")
    else:
        updated = current.rstrip() + "\n\n" + block
    bashrc.write_text(updated, encoding="utf-8")
    return {"path": str(bashrc), "status": "updated"}


def install_claude(repo_root: Path) -> dict[str, Any]:
    npm = node_bin(repo_root) / "npm"
    if not npm.exists():
        raise BootstrapError(f"npm not found: {npm}")
    env = os.environ.copy()
    env["PATH"] = f"{node_bin(repo_root)}:{env.get('PATH', '')}"
    env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0"
    log_path = tools_root(repo_root) / "install-claude.log"
    run_streamed(
        [str(npm), "install", "-g", CLAUDE_PACKAGE],
        cwd=repo_root,
        env=env,
        log_path=log_path,
    )
    return {"status": "installed", "package": CLAUDE_PACKAGE, "log": str(log_path)}


def rtk_asset_hint() -> list[str]:
    arch = platform.machine().lower()
    if arch in {"aarch64", "arm64"}:
        return ["aarch64-unknown-linux-gnu", "aarch64", "arm64", "linux"]
    if arch in {"x86_64", "amd64"}:
        return ["x86_64-unknown-linux-musl", "x86_64", "amd64", "linux"]
    return [arch, "linux"]


def resolve_rtk_download_url() -> dict[str, Any]:
    release = fetch_json(RTK_LATEST_RELEASE_API, insecure_ssl=True)
    assets = release.get("assets") or []
    hints = rtk_asset_hint()
    candidates: list[dict[str, Any]] = []
    for asset in assets:
        name = str(asset.get("name") or "")
        url = str(asset.get("browser_download_url") or "")
        lowered = name.lower()
        if not url:
            continue
        if all(hint in lowered for hint in hints if hint != "linux"):
            candidates.append({"name": name, "url": url})
        elif "linux" in lowered and any(hint in lowered for hint in hints):
            candidates.append({"name": name, "url": url})
    if not candidates:
        names = [str(asset.get("name") or "") for asset in assets]
        raise BootstrapError(
            "could not find a matching RTK Linux release asset; "
            f"available assets: {', '.join(names)}"
        )
    return {"release": release.get("tag_name"), **candidates[0]}


def extract_rtk_binary(archive: Path, target: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="rtk-extract-") as tmpdir:
        tmp = Path(tmpdir)
        if archive.name.endswith((".tar.gz", ".tgz")):
            with tarfile.open(archive, mode="r:gz") as tar:
                tar.extractall(tmp)
        else:
            shutil.copyfile(archive, tmp / "rtk")
        matches = [path for path in tmp.rglob("rtk") if path.is_file()]
        if not matches:
            raise BootstrapError(f"rtk binary not found in downloaded artifact: {archive}")
        shutil.copyfile(matches[0], target)


def install_rtk(repo_root: Path, *, rtk_url: str | None) -> dict[str, Any]:
    resolved: dict[str, Any] | None = None
    if not rtk_url:
        resolved = resolve_rtk_download_url()
        rtk_url = str(resolved["url"])
    target = node_bin(repo_root) / "rtk"
    artifact = tools_root(repo_root) / Path(rtk_url.split("?", 1)[0]).name
    download_file(rtk_url, artifact, insecure_ssl=True)
    extract_rtk_binary(artifact, target)
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    proc = run([str(target), "--version"], check=False)
    return {
        "status": "installed",
        "path": str(target),
        "artifact": str(artifact),
        "download_url": rtk_url,
        "release": resolved.get("release") if resolved else None,
        "asset": resolved.get("name") if resolved else None,
        "version": proc.stdout.strip() if proc.returncode == 0 else None,
    }


def copy_claude_settings(repo_root: Path, *, overwrite: bool) -> dict[str, Any]:
    src = repo_root / ".claude" / "settings.example.json"
    dest = Path.home() / ".claude" / "settings.json"
    if not src.exists():
        return {"status": "skipped", "reason": f"missing {src}"}
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and not overwrite:
        return {"status": "skipped", "reason": "settings.json already exists"}
    shutil.copyfile(src, dest)
    return {"status": "written", "path": str(dest), "source": str(src)}


def run_personal_setup(args: argparse.Namespace) -> dict[str, Any]:
    repo_root = ensure_repo_root(Path(args.repo_root))
    result: dict[str, Any] = {"repo_root": str(repo_root)}

    arch = platform.machine().lower()
    if arch not in {"aarch64", "arm64"} and not args.yes:
        section("Architecture warning")
        print(f"Current architecture is {arch}; requested Node archive is linux-arm64.")
        if not prompt_yes_no("Continue installing linux-arm64 Node?", default=False):
            raise BootstrapError("stopped because architecture is not arm64")

    section("Git identity")
    user_name = args.git_user_name or prompt_text("git config --global user.name", required=False)
    user_email = args.git_user_email or prompt_text("git config --global user.email", required=False)
    result["git_identity"] = configure_git_identity(
        user_name=user_name or None,
        user_email=user_email or None,
    )

    section("Git aliases")
    result["gitalias"] = configure_gitalias(repo_root)

    section("Node")
    result["node"] = install_node(repo_root, force=args.force_node)

    section("Claude")
    result["claude_install"] = install_claude(repo_root)
    overwrite_settings = args.yes or prompt_yes_no(
        "Replace ~/.claude/settings.json with this repo's Claude settings example?",
        default=True,
    )
    result["claude_settings"] = copy_claude_settings(repo_root, overwrite=overwrite_settings)

    section("DeepSeek / shell environment")
    deepseek_base_url = args.deepseek_base_url or prompt_text(
        "DeepSeek Anthropic-compatible base URL",
        default=DEFAULT_DEEPSEEK_BASE_URL,
    )
    deepseek_model = args.deepseek_model or prompt_text(
        "DeepSeek model for Claude env",
        default=DEFAULT_DEEPSEEK_MODEL,
    )
    deepseek_token = (
        getattr(args, "deepseek_token", None)
        or os.environ.get("DEEPSEEK_API_KEY")
        or os.environ.get("ANTHROPIC_AUTH_TOKEN")
        or prompt_secret("DeepSeek API token")
    )
    env_result = write_personal_env(
        repo_root,
        deepseek_base_url=deepseek_base_url,
        deepseek_model=deepseek_model,
        deepseek_token=deepseek_token,
    )
    result["personal_env"] = env_result
    result["bashrc"] = update_bashrc(Path(env_result["path"]))

    section("rtk")
    rtk_url = args.rtk_url or os.environ.get("RTK_DOWNLOAD_URL")
    result["rtk"] = install_rtk(repo_root, rtk_url=rtk_url)

    result["status"] = "ok"
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Personal container bootstrap.")
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--yes", action="store_true")
    parser.add_argument("--git-user-name")
    parser.add_argument("--git-user-email")
    parser.add_argument("--force-node", action="store_true")
    parser.add_argument("--deepseek-base-url")
    parser.add_argument("--deepseek-model")
    parser.add_argument("--rtk-url")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        print(json.dumps(run_personal_setup(args), indent=2, sort_keys=True))
        return 0
    except BootstrapError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
